appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OYI/ihs78uoj1nEcV62+N6VHnMOeMAw2vfw/Xfmc9M356hg3Q/gE4T5zo3DIUNCYwchAjREmCfqABalSzqaDyTbFbYxhRlxceZFpV86OlbhKjtL4nloxkTACTw/eS0YFUQuUBrHcRUgIa3keaip2hnN4ZVyL5GPDaE/qkH2KRGdu80UMzNFWTV17GcwCLAgGIDCWQT5BxJwa0zVst6qkxukvGiAo84fANALh20zjMMUi1DXVNB11g07CWKfy5y2LTY6m2PEsgzQpP2Ocn+M5w3KHWy/zg5xvuvEHVsjDImAgVCuedtSeZoEKQP2ZMCIMBzLhIN4ixGG6Qsz5A60yd2d9pu9ntVN5eU9xEzpDXGrVgSWA+ch2QHUFj4DNjfjQOwj4PAavzYnCgjhceeY/nIt9fPktVSHR2k3m/6remN8v6veXPE2GeTkUb0pvdgdaNntWFyk+t3J7UXazb3lbtR56tXJPJAVcwzXk80oihJ4ojPIuwMqf6NZG21X+Bys1h5DQUMut+TB0HnESyQTI+LIYaVlwX98KdTlILtHRrqM2s4GVVb0xeovwxY4oAaGxKXztG89WcDhTW8fhcDy5DMnoBQj5CD0VndFCudCgF3sGu16byz7gyJBDiEJvKMsHrEG9Utzq07MNcjYDcyrkUlA6vbAwfR1wxrJNT2YXHjA=}
bot:
  automerge: true
